spring:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quizlog_local
    username: gorilla
    password: gorilla

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
=======
=======
>>>>>>> Stashed changes
    application:
      name:QuizlogApplication

    datasource:
<<<<<<< Updated upstream
      url:jdbc:mysql://localhost:3306
>>>>>>> Stashed changes
=======
      url:jdbc:mysql://localhost:3306
>>>>>>> Stashed changes
